"""Génère json/bdd_p2023.json — BDD_DE_P2023_1 (TI603, 60 questions)."""
import json
from pathlib import Path

SOURCE = "DE P2023 - Bases de Données (TI603, 27/05/2021)"


def q(num, letters, question, options):
    multiple = len(letters) > 1
    idx = {c: i for i, c in enumerate("ABCDEF")}
    correct = [options[idx[c]] for c in letters if c in idx]
    row = {"id": f"p2023_{num:02d}", "question": question, "options": options, "sourceFile": SOURCE}
    if multiple:
        row["multiple"] = True
        row["correctAnswers"] = correct
    else:
        row["correctAnswer"] = correct[0]
    return row


RAW = [
    (1, "D",
     "La commande CREATE TABLE ord_items (voir contexte) retourne une erreur. Quelle en est la cause ?",
     ["La PRIMARY KEY ne peut pas être composée de deux attributs (ord_no, item_no)",
      "BETWEEN ne peut pas être utilisée dans une contrainte CHECK",
      "client_id n'est pas PRIMARY KEY dans la table orders",
      "client_id n'est pas unique dans la table orders",
      "La référence de la FOREIGN KEY ord_fk n'existe pas dans la table ORDERS"]),
    (2, "ABC",
     "Table T(A:int, B:int, C:int). Lesquelles des requêtes suivantes sont correctes par rapport au standard SQL ?",
     ["select B, count(A) from T group by A, B having count(B) > A",
      "select A, count(B) from T group by A, B having B = 0",
      "select A, count(C) from T group by A, B having max(C) = A",
      "select count(A), B from T group by B having A = B"]),
    (3, "A",
     "Un administrateur veut afficher les villes où count(*) > 10 000. Quelle requête SQL ?",
     ["SELECT ville, count(*) FROM table_ville GROUP BY ville HAVING count(*)>10000",
      "SELECT ville, count(*) FROM table_ville GROUP BY ville count(*)>10000",
      "SELECT ville, count(*) FROM table_ville GROUP BY ville WHERE count(id_ville)>10000",
      "SELECT ville, count(*) FROM table_ville GROUP BY ville WHERE count(*)>10000"]),
    (4, "DE",
     'SELECT Nom, Age FROM Etudiants WHERE Age > 20 ORDER BY Age permet de :',
     ["Classer les étudiants par ordre alphabétique",
      "Avoir le nombre d'étudiants de plus de 20 ans",
      "Lister les nom et âges de tous les étudiants",
      "Lister les noms et âges des étudiants de plus de 20 ans triés par âge",
      "Lister les noms et âges des étudiants de plus de 20 ans classés par âge",
      "Lister les noms et âges des étudiants de plus de 20 ans groupés par âge"]),
    (5, "D",
     "Sans type de verrou demandé lors d'une mise à jour de plusieurs lignes, quels verrous ?",
     ["Verrou exclusif sur la table (méthode la plus rapide)",
      "Pas de verrouillage — niveau par défaut NONE",
      "Verrous partagés sur la table et chaque ligne",
      "Verrou exclusif sur chaque ligne et verrou partagé sur la table"]),
    (6, "AC", "Laquelle de ces commandes mettra fin à une transaction ?",
     ["GRANT", "CREATE", "SET AUTOCOMMIT ON", "SAVEPOINT"]),
    (7, "CD", "Après UPDATE sur matable, quelle commande rend la modification permanente ?",
     ["Rien — le changement est permanent",
      "SET AUTOCOMMIT = 1",
      "GRANT SELECT ON matable TO ...",
      "COMMIT",
      "COMMIT matable"]),
    (8, "A", "Connexion L3A/L3B@L3C:3306/L3D — à quelle base êtes-vous connecté ?",
     ["L3D", "L3C", "L3B", "L3A"]),
    (9, "BD", "Deux utilisateurs consultent la même table. Quelles affirmations sont correctes ?",
     ["Ils ne voient jamais le même contenu",
      "Il est possible qu'ils ne voient pas le même contenu",
      "Ils voient toujours le même contenu",
      "Il est possible qu'ils voient le même contenu"]),
    (10, "A", "Quelle commande n'est pas valide dans une procédure stockée PL/SQL ?",
     ["RETURN", "LOOP", "DROP", "IF"]),
    (11, "AD", "Lesquelles ne font pas partie des fonctions de groupe SQL ?",
     ["AVERAGE", "MIN", "AVG", "MAXI"]),
    (12, "CD", "Quels types sont définis dans MySQL ?",
     ["DATE_TIME", "INTIGER", "CLOB", "BLOB"]),
    (13, "B",
     "Vue V_EMP (agrégation sur employees). UPDATE V_EMP SET SOMME=20000 WHERE DEPARTMENT_ID=20 — quel énoncé est correct ?",
     ["La colonne SOMME de la vue sera modifiée pour le département 20",
      "On ne peut pas modifier la colonne SOMME à partir de la vue V_EMP",
      "La colonne SOMME de EMPLOYEES sera modifiée pour le département 20",
      "La colonne SALARY de EMPLOYEES sera modifiée pour le département 20"]),
    (14, "BC",
     "Table T(A int PK, B int, C int). SELECT A, B FROM T renvoie le même résultat que :",
     ["select A, B from T where B is not null",
      "select A, B from T where A is not null",
      "select distinct A, B from T",
      "select A, B from T where A <> null"]),
    (15, "D", "Script de contrôle événementiel vers la BDD — de quel objet s'agit-il ?",
     ["Verrous", "Procédure stockée", "Vue", "Trigger"]),
    (16, "AD", "Quelle expression booléenne vaut true ?",
     ["'hello' like '%ello'", "'hello' = '_hello'", "'hello' like 'h%l%l'", "'hello' like '%hello'"]),
    (17, "AB",
     "SCOTT : deadlock sur UPDATE EMP causé par JIM. Deux affirmations vraies sur la session SCOTT ?",
     ["SCOTT doit réexécuter la dernière commande après avoir validé la transaction",
      "SCOTT doit faire COMMIT ou ROLLBACK pour permettre à JIM de poursuivre",
      "La session est terminée et JIM peut poursuivre",
      "La session est annulée et JIM peut poursuivre"]),
    (18, "AB", "Table T(A int PK, B int). Quelle requête peut produire des doublons ?",
     ["select B from T", "select B from T where B = 0", "select * from T", "select A from T where A = 0"]),
    (19, "BD", "Table T(A,B,C). Requêtes correctes selon le standard SQL ?",
     ["select C, count(A) from T group by A, B",
      "select A, count(B) from T group by A, B",
      "select A, B from T group by B",
      "select A, count(C) from T group by A, B"]),
    (20, "AD", "Tables Pieces et Produits — quelles contraintes mettre en place ?",
     ["FK sur Numéro produit dans Pieces",
      "FK sur Numéro pièce dans Produits",
      "UNIQUE sur Numéro pièce dans Pieces",
      "UNIQUE sur Numéro produit dans Produits"]),
    (21, "AB", "ORDER BY — deux affirmations correctes ?",
     ["Combinaison possible avec opérations arithmétiques",
      "C'est la dernière clause d'une requête SELECT",
      "S'exécute en premier",
      "S'exécute seulement avec HAVING"]),
    (22, "BD", "Affirmations vraies sur NULL ?",
     ["NULL ne s'applique qu'aux types numériques",
      "NULL signifie valeur manquante ou non applicable",
      "NULL et 'NULL' sont équivalents",
      "NULL et null sont équivalents"]),
    (23, "B",
     "Erreur sur : SELECT promo_categorie, AVG(promo_prix) AS MOYPRIX, AVG(promo_prix)*.25 AS MOYPROMO FROM PROMOTIONS ... GROUP BY MOYPRIX ORDER BY MOYPROMO — quelle clause ?",
     ["ORDER BY", "GROUP BY", "SELECT", "WHERE"]),
    (24, "D", "Commande SQL modifiant la structure de MyTable :",
     ["UPDATE TABLE MyTable", "UPDATE MyTable", "ALTER MyTable", "ALTER TABLE MyTable"]),
    (25, "DE", "Package java.sql pour exécuter un UPDATE MySQL depuis Java ?",
     ["preparedStatement", "CallableStatement", "Connexion", "Statement", "PreparedStatement"]),
    (26, "B",
     "CLIENTS : client_ville='Paris', prenom='ABIGAIL'. Résultat de SELECT INITCAP(client_prenom||' '||UPPER(SUBSTR(client_ville,LENGTH(client_ville),2))) ... ?",
     ["Abigail IS", "Abigail Pa", "Abigail PA", "Un message d'erreur"]),
    (27, "CD", "Tables T(A,B) et S(B,C). Affirmations vraies ?",
     ["T natural left outer join S contient au moins autant de tuples que T natural right outer join S",
      "T natural inner join S contient plus de tuples que T natural join S",
      "T natural outer join S contient au moins autant de tuples que T natural left outer join S",
      "T natural outer join S contient au moins autant de tuples que T natural join S"]),
    (28, "B", "Une vue est tout simplement une requête SELECT à laquelle on donne un nom.",
     ["Faux", "Vrai"]),
    (29, "AD", "Commandes définissant une clé primaire sur latable ?",
     ["ALTER TABLE latable MODIFY CONSTRAINT ...",
      "CREATE TABLE latable (PK_Table PRIMARY KEY ...)",
      "CREATE TABLE latable (lacolonne PRIMARY KEY ...)",
      "ALTER TABLE latable ADD CONSTRAINT ..."]),
    (30, "C",
     "Script : CREATE ROLE; GRANT CREATE table; GRANT SELECT table; GRANT CONNECT — quelle ligne erreur ?",
     ["Ligne 4 : rôle ne peut pas avoir privilège système + table",
      "Ligne 2 : seuls utilisateurs peuvent créer tables",
      "Ligne 3 : SELECT TABLE n'est pas un privilège",
      "Ligne 1 : seuls utilisateurs ont des mots de passe"]),
    (31, "A", "Les commandes GRANT et REVOKE s'appliquent sur :",
     ["Les vues et les tables", "Les vues matérialisées et les tables uniquement", "Les vues uniquement", "Les tables uniquement"]),
    (32, "AB", "Commandes créant la vue V1 :",
     ["CREATE VIEW V1 ...", "CREATE OR REPLACE VIEW V1 ...", "REPLACE VIEW V1 ...", "INSERT VIEW V1 ..."]),
    (33, "CD", "À quoi sert une vue ?",
     ["Assurer la concurrence d'accès", "Assurer la tolérance aux pannes",
      "Simplifier les requêtes complexes", "Assurer l'indépendance logique"]),
    (34, "BD", "Validation implicite des transactions sous MySQL ?",
     ["À chaque opération si AUTOCOMMIT vaut 0",
      "Lors de la déconnexion (fermeture session)",
      "Lors de la déconnexion suite à une panne",
      "À chaque opération si AUTOCOMMIT vaut 1"]),
    (35, "CF", 'Expression "A between 10 and 100" (A int) équivalente à :',
     ["10 < A and A <= 100", "10 <= A <= 100", "100 >= A and A >= 10",
      "100 > A and A > 10", "10 <= A and A < 100", "10 <= A and A <= 100"]),
    (36, "B", "Quel privilège système permet de se connecter à une base ?",
     ["Create session", "Create user", "Grant", "Create table"]),
    (37, "B", "Si X => Y et X => Z, quelle affirmation est vraie ?",
     ["Y => Z", "X => Y,Z", "Y,Z => X", "Z => Y"]),
    (38, "B", 'Quelle dépendance est dite "triviale" ?',
     ["A,B -> C", "A,B -> B", "B,C -> C,D", "A -> A,C"]),
    (39, "C", "Si X => Y et W,Y => Z, quelle affirmation est vraie ?",
     ["X => Z", "Z => X", "W,X => Z", "Y => Z"]),
    (40, "B",
     "SALARIES, STAGE, EFFECTUER (voir contexte). Un salarié ne peut faire qu'un seul stage — vrai ou faux ?",
     ["Vrai", "Faux"]),
    (41, "A",
     "EMPLOYE(Num, Nom, Catégorie, Salaire), Num PK, Catégorie -> Salaire. Corriger pour 3FN ?",
     ["Décomposer en EMPLOYE et SALAIRE", "Supprimer Catégorie", "Ajouter CategorieSalaire", "Pas de problème"]),
    (42, "B", "Si X => Y et Y => Z, quelle affirmation est vraie ?",
     ["Y => X", "X => Z", "Y => Y", "Z => X"]),
    (43, "BD", "Vrai concernant les associations dans un MCD ?",
     ["Une association est toujours transformée en table",
      "Une association peut être transformée en table",
      "Une association n'est jamais transformée en table",
      "Une association peut engendrer une clé primaire composée"]),
    (44, "AC",
     "R(A,B,C,D), clé AB, F={AB->CD, A->B, D->CB}. Ce schéma est en :",
     ["1ère Forme Normale", "3ème Forme Normale", "2ème Forme Normale", "n'est pas en 1FN"]),
    (45, "ADE", "Quelles propriétés font partie d'ACID ?",
     ["Durabilité", "Concurrence", "Cooperation", "Isolation", "Atomicité"]),
    (46, "A",
     "CLIENT(numero, nom, prenom, dateDinscription), PK numero. Pourquoi prenom dépend de numero ?",
     ["À une valeur de numero correspond une seule valeur de prenom",
      "À partir du prénom on retrouve le numéro",
      "Un client peut avoir plusieurs prénoms",
      "Chaque ligne concerne un client identifié par prenom"]),
    (47, "D",
     "Couverture minimale ? 1:NomClient->TypeClient 2:TypeClient->CategorieClient 3:NomClient->CategorieClient 4:NumCommande->DescCommande 5:NumCommande,NomClient->DateCommande",
     ["{1,3,4,5}", "{1,2,5}", "{1,3,4}", "{1,2,4,5}"]),
    (48, "AB", "Quelles appellations ne sont pas utilisées dans un MCD ?",
     ["Objet", "Fonction", "Entité", "Attribut"]),
    (49, "BC",
     "R(A,B,C,D,E), DF={AB->CDE; B->C; AC->BDE; C->BD; B->E}. Clé(s) candidate(s) ?",
     ["B,C", "A,B", "A,C", "A,B,C"]),
    (50, "C", "Dans un MCD, qu'est-ce qu'une cardinalité ?",
     ["Élément identifiant un tuple",
      "Rôle entre association et entité",
      "Nombre min et max d'instances dans la relation",
      "Relation logique entre deux tables"]),
    (51, "B",
     "CLIENT/Num_client, FACTURE/Num_facture FK Num_client. Une facture ne concerne qu'un seul client ?",
     ["Non", "Oui"]),
    (52, "A",
     "PRODUIT(Codeprod, Numcat, Nomprod), PK (Codeprod, Numcat), FK Numcat. En 2FN ?",
     ["Non", "Oui"]),
    (53, "B", "Dans un modèle relationnel, une table peut contenir plusieurs tuples identiques.",
     ["Vrai", "Faux"]),
    (54, "B", "Quelle forme normale exige l'absence de DF entre attributs non clés ?",
     ["2FN", "3FN", "Aucune des 3 premières", "1FN"]),
    (55, "BD", "Contraintes d'intégrité dans une BDD :",
     ["Contrainte d'agrégation", "Contrainte de clé primaire",
      "Contrainte de généralisation/spécialisation", "Contrainte de domaine"]),
    (56, "BD",
     "Contraintes pour une décomposition en 3FN autorisée ?",
     ["Nombre de relations obtenues ne doit pas dépasser 2",
      "Couverture minimale des DF conservée",
      "Toutes les DF doivent être conservées",
      "Décomposition sans perte"]),
    (57, "ABC",
     "CLIENT(numero PK, nom, prenom, dateDinscription). Pourquoi dateDinscription ne dépend pas de prenom ?",
     ["Un attribut ne dépend que d'un attribut clé primaire",
      "On ne peut pas déterminer le client par le prénom seul",
      "Un même prénom peut correspondre à plusieurs dates d'inscription",
      "DF uniquement entre attributs de même domaine"]),
    (58, "C",
     "CLIENT/COMMANDE (FK numeroDuClient). Cardinalité côté Client dans le MCD ?",
     ["(1,1)", "(n,m)", "(0,n)", "(0,1)"]),
    (59, "A", "Comment représente-t-on une contrainte d'intégrité référentielle ?",
     ["Une clé étrangère", "Une clé primaire", "Clé étrangère + clé primaire", "Une clé composée"]),
    (60, "D", "Une relation est en 1FN si :",
     ["La clé est un attribut unique",
      "Les attributs de la clé sont atomiques",
      "Un attribut dépend de la totalité de la clé",
      "Tous ses attributs sont atomiques"]),
]

questions = [q(n, l, text, opts) for n, l, text, opts in RAW]
Path(__file__).parent.joinpath("json").mkdir(exist_ok=True)
out = Path(__file__).parent / "json" / "bdd_p2023.json"
out.write_text(json.dumps(questions, ensure_ascii=False, indent=2), encoding="utf-8")
print("OK", len(questions))
