"""Génère json/bdd_de_bdd.json — DE_BDD.pdf (TI503, 27/11/2021, 50 questions)."""
import json
from pathlib import Path

SOURCE = "DE BDD - TI503 Bases de Données Avancées (27/11/2021)"


def q(num, letters, question, options):
    idx = {c: i for i, c in enumerate("ABCDEFG")}
    correct = [options[idx[c]] for c in letters if c in idx]
    row = {"id": f"de_bdd_{num:02d}", "question": question, "options": options, "sourceFile": SOURCE}
    if len(letters) > 1:
        row["multiple"] = True
        row["correctAnswers"] = correct
    else:
        row["correctAnswer"] = correct[0]
    return row


RAW = [
    (1, "B", "Une table est en 2FN si elle est en 1FN et :",
     ["Il n'y a pas de valeurs nulles dans les champs de la clé primaire",
      "Il n'y a pas d'attributs qui ne dépendent pas fonctionnellement de toute la clé primaire",
      "Il n'y a pas de groupes répétitifs",
      "Il n'y a pas de dépendances fonctionnelles"]),
    (2, "AB", "En normalisant une relation en deux relations, que faire pour l'intégrité ?",
     ["Créer une ou plusieurs clés primaires pour la nouvelle relation",
      "Relier les relations par un champ commun",
      "Supprimer toute dépendance fonctionnelle des deux relations",
      "Attribuer aux deux relations le même champ de clé primaire"]),
    (3, "A", "Entité Personne (ID_Personne, Nom, ADRESSE_RUE_VILLE_CP) — on peut dire que :",
     ["Aucune des autres réponses", "Elle est en 1FN", "Elle est en 3FN", "Elle est en 2FN"]),
    (4, "C",
     "Employe(NumE PK, NumDep, NumChef, Nom...). SELECT Nom FROM Employe WHERE NumChef IS NULL — résultat ?",
     ["Aucun résultat (FK ne peut être NULL)",
      "Erreur (FK ne peut être NULL)",
      "Nom du PDG (employé sans patron)",
      "Tous les noms d'employés"]),
    (5, "B", "La clé primaire d'une entité peut être composée de plusieurs champs :", ["Non", "Oui"]),
    (6, "A", "Les cardinalités déterminent le :",
     ["Le nombre min et max de fois qu'une entité peut participer à une relation",
      "L'intervalle des valeurs d'un attribut",
      "Le nombre min et max de tables liées par une relation"]),
    (7, "B", "Une relation dans un MCD est transformée en une table dans le MLD :",
     ["Oui", "Pas nécessairement", "Non"]),
    (8, "C", "Dans les SGBD relationnels, la normalisation permet de :",
     ["Vérifier une norme CE/ISO", "Vérifier la conformité aux opérations de l'entreprise",
      "Minimiser la redondance et assurer la cohérence", "Aucune des autres réponses"]),
    (9, "D", "Commandes ORDER sans client correspondant dans CUSTOMER :",
     ["Select order_id from CUSTOMER where order_id NOT IN (select customer_id from CUSTOMER)",
      "Select * from ORDER where all customer is null",
      "Select order_id from ORDER where order_id is null",
      "Select order_id from ORDER where customer_id NOT IN (select customer_id from CUSTOMER)"]),
    (10, "D", "Élément pour créer/supprimer la structure des relations :",
     ["TCL", "DCL", "DML", "DDL"]),
    (11, "AD", "Pour créer une requête en BDD relationnelle, je dois connaître :",
     ["La ou les tables utilisées", "Le nombre d'enregistrements", "La date de création de la BDD", "Les champs dont j'ai besoin"]),
    (12, "AC", "Une clé primaire :",
     ["Est un champ qui n'accepte pas les doublons", "Est toujours le premier enregistrement",
      "Permet d'identifier de façon unique un enregistrement"]),
    (13, "B", "Dans une BDD, une clé primaire est utilisée pour :",
     ["Enregistrer une base de données", "Identifier les informations pour les retrouver", "Désigner un programme"]),
    (14, "C", "Qu'est-ce que le langage SQL ?",
     ["Langage de conception", "Langage de description de documents",
      "Langage de manipulation des données (interactif ou hôte)", "Langage de modélisation conceptuelle"]),
    (15, "C", "Laquelle contient une erreur ?",
     ["Select empid from emp where empid = 89",
      "Select * from emp where empid = 107",
      "Select empid where empid = 176 and lastname = 'GELLER'",
      "Select empid from emp"]),
    (16, "A", "Commande pour supprimer une relation en SQL :", ["Drop table", "Delete", "Purge", "Remove"]),
    (17, "B", "Avec UNION, chaque requête doit produire le même nombre de colonnes compatibles :", ["Faux", "Vrai"]),
    (18, "B", "L'opération ___ fusionne des tuples de deux relations en un tuple :", ["Union", "Join", "Intersection", "Select"]),
    (19, "C", "L'opérateur ___ renvoie les lignes présentes dans les deux résultats :", ["Difference", "Projection", "Intersect", "Union"]),
    (20, "C", "Dans quelle FN un attribut composite est converti en attributs individuels ?", ["2FN", "3FN", "1FN"]),
    (21, "A", "AUTOCOMMIT activé : modifications automatiques en fin de chaque instruction SQL :", ["Vrai", "Faux"]),
    (22, "A",
     "Vue ordersview (jointure orders, customer, agents). UPDATE ordersview SET cust_name='Harry' WHERE ord_num=121137 :",
     ["Impossible : vue avec jointures non modifiable", "Met à jour tous les customer où ord_num=121137",
      "Met à jour uniquement clients dans la vue", "Une vue ne peut jamais être mise à jour"]),
    (23, "A", "Instruction pour supprimer les droits d'un utilisateur :", ["REVOKE", "REMOVE", "UNGRANT", "FORBID"]),
    (24, "D", "Qu'est-ce qu'une transaction ?",
     ["Un groupe de données dans la même structure", "Jeu de résultats d'une requête stockée",
      "Structure pour retrouver rapidement des données",
      "Séquence d'opérations : tout valider ou tout annuler"]),
    (25, "B", "Niveau d'isolation qui n'existe pas dans MySQL InnoDB :",
     ["REPEATABLE READ", "COMMITABLE", "READ UNCOMMITTED", "SERIALIZABLE"]),
    (26, "B",
     "autocommit=false : 3 INSERT, ROLLBACK, 2 INSERT, COMMIT, 1 INSERT — quels enregistrements dans Person ?",
     ["Aucun", "Seules Mary et Dorra", "Tous", "Hellen, Gary, Wayne, Mary et Dorra", "Mary, Dorra et Suzy", "Hellen, Gary et Wayne"]),
    (27, "D", "MCD Employee/Department (voir contexte) — affirmation correcte :",
     ["Un employé peut travailler dans plusieurs départements",
      "Un employé peut n'appartenir à aucun département", "Un département peut ne pas avoir d'employés",
      "Un employé ne travaille que dans un seul département"]),
    (28, "C", "MCD — is_manager_of / Department :",
     ["Un employé manager de plusieurs départements", "Chaque employé manager d'au moins un département",
      "Chaque département a au moins un manager", "Un manager peut être d'un autre type qu'employé"]),
    (29, "CE", "MCD — Department / Project / works_on :",
     ["Un projet doit appartenir à un département", "Chaque département a au moins un projet",
      "Un département peut avoir plusieurs projets", "Chaque employé travaille sur au moins un projet",
      "Un projet a au moins un employé qui travaille dessus"]),
    (30, "B", "Combien de tables en passant ce MCD en MLD ?", ["9", "7", "6", "4"]),
    (31, "A", "Combien d'attributs la table « has » contiendra-t-elle ?", ["2", "Aucune (pas de table has)", "3", "1"]),
    (32, "C", "Vrai ou faux : is_manager_of devient une table dans le MLD ?",
     ["Vrai (relation 1-1)", "Faux (pas N-N)", "Vrai (attribut since)", "Faux (employé zéro département)"]),
    (33, "B", "Affirmation correcte (Employee / Child / in_charge_of) :",
     ["Employee aura FK Child_id", "Child aura FK Employee_id", "in_charge_of aura FK Child_id et Employee_id"]),
    (34, "B", "Dans le MLD, la table Employee contient une et une seule clé étrangère :", ["Faux", "Vrai"]),
    (35, "B", "Design 1 (voir contexte) — quelle FN respecte-t-il initialement ?", ["1FN", "Aucune", "1FN et 3FN", "2FN"]),
    (36, "ACE", "Design 1 — affirmations correctes :",
     ["Une commande ne concerne qu'un seul client", "Une commande peut avoir plusieurs dates",
      "Une commande peut avoir plusieurs quantités", "Une commande dans plus d'un État",
      "Une commande peut contenir plusieurs produits"]),
    (37, "ABEG", "Design 1 — colonne(s) ne respectant pas la 1FN ?",
     ["Qty", "PID", "Aucune (respecte 1FN)", "CID", "P_Desc", "C_Name", "P_Price"]),
    (38, "D", "Combien de tables après normalisation du Design 1 (voir DF) ?", ["5", "3", "2", "4"]),
    (39, "C", "Design 2 — clé candidate de Order ?", ["{OID, CID}", "CID", "{OID, PID}", "PID", "OID"]),
    (40, "B", "Design 2 respecte quelle FN ?", ["3FN", "1FN", "Aucune", "2FN"]),
    (41, "A", "Quelle DF brise la 2FN dans Design 2 ?", ["OID -> CID", "CID -> C_Name", "PID, OID -> Qty", "Aucune (déjà 2FN)"]),
    (42, "B", "Affirmation correcte sur Design 2 :",
     ["Design 2 est 3FN", "Order n'est pas 2FN donc Design 2 n'est pas 3FN",
      "Pas 3FN car Qty ne dépend que de la commande", "Pas 3FN car CID dépend de PID"]),
    (43, "D", "Décomposer Order (Design 2) pour obtenir 2FN :",
     ["Design 2 déjà 2FN",
      "Order_Customer (OID,CID) + Order_Product (OID,PID,O_Date,Qty)",
      "Order (OID,O_Date) + Order_Customer (OID,PID,CID) + Order_Product (OID,PID,Qty)",
      "Order (OID, CID, O_Date) + Order_Product (OID, PID, Qty)"]),
    (44, "A", "Films en français (schéma FILM/PERSON — voir contexte) :",
     ["select * from FILM where language='French'", "insert details into FILM where language='French'",
      "select * from FILM, PERSON where language='French'", "select details from FILM where language='French'"]),
    (45, "ABC", "Nom(s) des acteurs du film 'Subway' :",
     ["select name from FILM, PERSON, PLAYS_IN where FILM.id=PLAYS_IN.id_film and PERSON.id=PLAYS_IN.id_person and FILM.title='Subway'",
      "select name from FILM join PERSON join PLAYS_IN on FILM.id=PLAYS_IN.id_film and PERSON.id=PLAYS_IN.id_person where FILM.title='Subway'",
      "select name from FILM f, PERSON p, PLAYS_IN pi where f.id=pi.id_film and p.id=pi.id_person and f.title='Subway'"]),
    (46, "C", "Pays des films budget > 50000000 (chaque pays une fois) :",
     ["select country from FILM where budget>50000000 and display='ONCE'",
      "select UNIQUE country from FILM where budget>50000000",
      "select DISTINCT country from FILM where budget>50000000"]),
    (47, "A", "Titre et année des films sortis entre 1990 et 2000 (inclus) :",
     ["select title, release_year from FILM where release_year between 1990 and 2000",
      "select title, release_year from FILM where release_year>1990 and release_year<2000",
      "select title, release_year from PERSON where release_year>=1990 and release_year<=2000"]),
    (48, "B",
     "Que fait : select country, SUM(budget) from FILM where release_year>2000 group by country having AVG(budget)>10000000 ?",
     ["Budget total films après 2000 avec budget > 10M par pays",
      "Par pays : budget total après 2000 si budget moyen du pays > 10M",
      "Par pays : budget total si chaque film > 10M en moyenne"]),
    (49, "C", "select name as director from PERSON join DIRECTS using(id_person) :",
     ["Crée colonne director dans PERSON", "Noms des réalisateurs",
      "Erreur : pas de colonne id_person dans PERSON", "Erreur : DIRECTS ne peut pas joindre PERSON"]),
    (50, "BD", "Équivalent(s) de : select * from FILM where release_year between 1990 and 2000",
     ["release_year >= 1990 OR release_year <= 2000",
      "release_year >= 1990 AND release_year <= 2000",
      "release_year >= 1990 UNION release_year <= 2000",
      "release_year >= 1990 INTERSECT release_year <= 2000"]),
]

out = Path(__file__).parent / "json" / "bdd_de_bdd.json"
out.write_text(json.dumps([q(n, l, t, o) for n, l, t, o in RAW], ensure_ascii=False, indent=2), encoding="utf-8")
print("OK", len(RAW))
