import json
from pathlib import Path

SOURCE = "DE 24-25 - Bases de Données Avancées (TI603)"

# Questions et réponses extraites du sujet corrigé (PDF 81823)
RAW = [
    (1, False, "B", "Dans une base de données utilisant un index B+ Tree pour une table avec des millions d'enregistrements, quelle situation pourrait réduire significativement l'efficacité de l'index ?",
     ["Une requête SELECT avec un filtre sur une colonne indexée ayant une faible cardinalité.",
      "Une requête UPDATE modifiant fréquemment la colonne indexée.",
      "Une requête JOIN utilisant l'index pour trier les résultats.",
      "Une requête GROUP BY sur une colonne non indexée."]),
    (2, True, "AC", "Quelles affirmations sont correctes concernant les vues matérialisées dans une base de données relationnelle ?",
     ["Elles stockent physiquement les données et occupent de l'espace disque.",
      "Elles ne sont créées que lorsqu'on les appelle",
      "Elles peuvent être utilisées pour améliorer les performances des requêtes complexes.",
      "Un update sur les tables de base pour une vue matérialisée prend moins de temps que pour une vue virtuelle."]),
    (3, False, "A", "Dans un système de gestion de base de données, une exécution est dite sérialisable par conflit si :",
     ["Elle est équivalente à une exécution séquentielle des transactions sans aucun conflit.",
      "Les transactions n'ont aucun accès concurrent aux mêmes données.",
      "Le graphe de précédence des transactions est cyclique mais sans interblocage.",
      "Les verrous sont appliqués sans respecter la règle des deux phases."]),
    (4, True, "BCD", "Quelles anomalies peuvent survenir dans une exécution de transactions avec un niveau d'isolation READ COMMITTED ?",
     ["Dirty read", "Non-repeatable read", "Phantom read", "Partially lost update"]),
    (5, False, "B", "Dans MySQL, quelle est la principale différence entre une procédure stockée et un trigger ?",
     ["Une procédure stockée est exécutée automatiquement à la suite d'un événement, contrairement à un trigger.",
      "Un trigger est défini pour une table spécifique et s'exécute en réponse à des opérations DML, contrairement à une procédure stockée.",
      "Une procédure stockée ne peut pas accepter de paramètres, contrairement à un trigger.",
      "Un trigger peut être appelé explicitement par un utilisateur, contrairement à une procédure stockée."]),
    (6, False, "A", "Lors de l'application de l'algorithme de synthèse pour normaliser une relation en 3e forme normale (3FN), que faut-il faire si une dépendance fonctionnelle entre deux attributs non clef est détectée ?",
     ["Supprimer la dépendance en créant une nouvelle relation avec les attributs concernés.",
      "Regrouper les attributs dans une seule relation pour préserver toutes les dépendances.",
      "Ignorer la dépendance si elle inclut une clé candidate.",
      "Modifier la clé primaire pour inclure les attributs de la dépendance transitive."]),
    (7, False, "B", "Dans une base de données relationnelle, quelle règle s'applique généralement à la modification des données via une vue logique définie sur une seule table ?",
     ["Les modifications sont toujours interdites pour préserver l'intégrité des données.",
      "Les modifications ne sont pas possibles si la vue contient des colonnes renommées.",
      "Les modifications nécessitent une vue matérialisée pour être valides.",
      "Les modifications sont permises uniquement si la vue inclut des colonnes calculées."]),
    (8, False, "A", "Dans le protocole de verrouillage en deux phases (2PL), quelle condition garantit qu'une exécution est exempte d'interblocage ?",
     ["Toutes les transactions acquièrent leurs verrous avant de commencer leur exécution.",
      "Les transactions libèrent tous leurs verrous avant d'en acquérir de nouveaux.",
      "Aucune condition ne garantit l'absence d'interblocage dans 2PL.",
      "Les verrous sont appliqués uniquement sur les données modifiées par la transaction."]),
    (9, True, "ABC", "Quelles affirmations sont correctes concernant les triggers dans MySQL ?",
     ["Un trigger peut être défini pour s'exécuter avant ou après une opération INSERT.",
      "Un trigger peut être utilisé pour appliquer des contraintes d'intégrité complexes.",
      "Un trigger peut appeler une procédure stockée.",
      "Un trigger peut être déclenché par une procédure stockée"]),
    (10, False, "D", "Lors de la décomposition d'une relation R(A, B, C, D) avec les dépendances fonctionnelles {A -> B, B -> C, A -> D} pour atteindre la 3e forme normale (3FN), quelle relation est créée pour éliminer la dépendance transitive B -> C ?",
     ["R1(A, C, D) et R2(B, C)", "R1(A, B, C) et R2(A, D)", "R1(A, B, D) et R2(A, C)", "R1(A, B, D) et R2(B, C)"]),
    (11, True, "AC", "Quelles affirmations sont correctes concernant les droits d'accès sur une vue dans une base de données relationnelle ?",
     ["Les droits sur une vue peuvent être définis indépendamment de la table de base.",
      "Un utilisateur ayant un accès SELECT sur une vue peut toujours modifier les données de la table de base.",
      "L'utilisation des vues peut restreindre l'accès à certaines colonnes de la table de base.",
      "Les vues héritent automatiquement des droits d'accès de la table de base."]),
    (12, False, "C", "Dans une base de données, quelle propriété ACID est directement compromise si une transaction lit des données modifiées par une autre transaction non validée (dirty read) ?",
     ["Atomicité", "Cohérence", "Isolation", "Durabilité"]),
    (13, False, "A", "Quel mécanisme peut être utilisé pour garantir la sérialisabilité des transactions dans une base de données ?",
     ["Verrouillage en deux phases (2PL)",
      "Mettre le niveau d'isolation à \"READ UNCOMMITTED\"",
      "Verrouillage exclusif sur toutes les tables accédées",
      "Journalisation WAL (Write-Ahead Logging)"]),
    (14, False, "C", "Dans MySQL, quelle clause est obligatoire dans la définition d'un trigger pour spécifier le moment de son exécution ?",
     ["FOR EACH ROW", "ON UPDATE", "BEFORE ou AFTER", "CALL"]),
    (15, False, "B", "Lors de l'application de l'algorithme de décomposition pour normaliser une relation en 2e forme normale (2FN), quelle condition doit être satisfaite pour chaque sous-relation ?",
     ["Chaque sous-relation doit contenir au moins une clé candidate composée.",
      "Les attributs non-clés dépendent pleinement de la clé entière",
      "Les attributs non-clés ne doivent pas dépendre d'autres attributs non clef",
      "Chaque sous-relation doit avoir une clé primaire unique (non composée)."]),
    (16, True, "ACD", "Dans quelles situations un index B+ Tree est-il particulièrement avantageux ?",
     ["Requêtes SELECT avec des conditions WHERE sur des colonnes indexées.",
      "Requêtes INSERT intensives sur une table avec des données non ordonnées.",
      "Requêtes de recherche par plage sur une colonne indexée.",
      "Requêtes JOIN impliquant des colonnes indexées."]),
    (17, False, "B", "Dans un SGBD, quel mécanisme permet de garantir la durabilité (D de ACID) ?",
     ["Les verrous exclusifs (X) sur les données modifiées.",
      "L'écriture préalable dans un journal (WAL).",
      "La validation en deux phases (2PC).",
      "L'utilisation de vues matérialisées."]),
    (18, True, "BD", "Lesquelles des affirmations suivantes sont vraies concernant la normalisation par synthèse ?",
     ["Elle commence par une table dénormalisée",
      "Elle commence par déterminer un ensemble de dépendances fonctionnelles minimales.",
      "Elle peut produire une décomposition qui ne préserve pas les dépendances fonctionnelles.",
      "Elle garantit une base de données en 3FN si les dépendances sont respectées."]),
    (19, False, "C", "Quel est le principal avantage d'un index B-Tree dans une base de données relationnelle ?",
     ["Il permet une suppression plus rapide des tuples.",
      "Il garantit une réduction de la taille physique de la table.",
      "Il permet un accès logarithmique aux données triées.",
      "Il offre un contrôle d'accès plus fin aux utilisateurs."]),
    (20, True, "AB", "Concernant les triggers en SQL, quelles sont les affirmations correctes ?",
     ["Un trigger peut être activé avant ou après une opération DML.",
      "Un trigger peut modifier la table qui l'a déclenché.",
      "Un trigger peut être déclenché par une requête SELECT.",
      "Plusieurs triggers sur un même événement doivent avoir un ordre d'exécution défini."]),
    (21, False, "A", "On vous donne la relation suivante : ÉTUDIANT(N°Étudiant, Nom, CodeCours, NomCours, Note). Sachant qu'un étudiant peut suivre plusieurs cours, qu'un cours a un seul nom, et qu'un étudiant a un seul nom, quelle est la forme normale maximale respectée par cette relation ?",
     ["1FN", "2FN", "3FN", "Aucune"]),
    (22, False, "C", "Vous devez créer un trigger qui refuse l'insertion d'un employé avec un salaire supérieur à celui de son supérieur hiérarchique. À quel moment le trigger doit-il être exécuté ?",
     ["AFTER INSERT", "AFTER UPDATE", "BEFORE INSERT", "INSTEAD OF INSERT"]),
    (23, True, "ABC", "Vous gérez un trigger qui enregistre dans une table de log chaque suppression de ligne dans une table CLIENTS. Lequel de ces éléments devez-vous inclure dans le trigger ?",
     ["La clause AFTER DELETE", "L'accès à OLD.id_client", "Une requête d'insertion dans la table LOG", "La condition IF OLD IS NOT NULL"]),
    (24, True, "AD", "Dans le processus de normalisation par décomposition, quels sont les objectifs principaux recherchés ?",
     ["Réduire la redondance des données", "Supprimer les clés étrangères", "Augmenter le volume de données stockées", "Éliminer les anomalies de mise à jour"]),
    (25, False, "D", "Quelle affirmation est correcte à propos des vues définies avec l'option WITH CHECK OPTION ?",
     ["Elle empêche toute mise à jour sur la vue.",
      "Elle interdit les suppressions d'enregistrements via la vue.",
      "Elle force la mise à jour automatique des vues matérialisées.",
      "Elle garantit que toute modification respecte la condition de définition de la vue."]),
    (26, False, "B", "Quel type d'isolation garantit qu'aucune transaction ne pourra lire des données modifiées mais non validées par une autre transaction ?",
     ["Read Uncommitted", "Read Committed", "Repeatable Read", "Serializable"]),
    (27, True, "ABCD", "Parmi les propriétés suivantes, lesquelles s'appliquent aux procédures stockées dans MySQL ?",
     ["Elles sont stockées sur le serveur",
      "Elles peuvent renvoyer des valeurs avec le mot-clé RETURN",
      "Elles peuvent contenir des structures conditionnelles et itératives",
      "Elles peuvent être appelées depuis un trigger"]),
    (28, False, "D", "Soit une relation R(A, B, C, D) avec les dépendances fonctionnelles {A -> B, A -> C, B -> D}. Quelle étape est essentielle pour normaliser cette relation en 2e forme normale (2FN) ?",
     ["Créer une nouvelle relation contenant uniquement les attributs A et D.",
      "Regrouper les attributs B et C dans une sous-relation distincte.",
      "Ajouter une clé candidate pour éliminer les dépendances partielles.",
      "Créer une nouvelle relation contenant B et D uniquement"]),
    (29, False, "C", "Dans une base de données avec un index B+ Tree sur une colonne fréquemment utilisée dans des requêtes WHERE, quelle situation pourrait justifier la suppression de cet index ?",
     ["La colonne indexée est rarement modifiée par des opérations UPDATE.",
      "Les requêtes SELECT sur cette colonne sont principalement des recherches par valeur exacte.",
      "La table subit des insertions massives, entraînant un coût élevé de maintenance de l'index.",
      "La colonne indexée a une cardinalité élevée, optimisant les recherches."]),
    (30, True, "AC", "Quelles affirmations sont correctes concernant les vues logiques dans une base de données relationnelle ?",
     ["Elles peuvent être utilisées pour masquer certaines colonnes d'une table à des utilisateurs.",
      "Elles permettent toujours des modifications si elles sont basées sur une seule table.",
      "Elles ne stockent pas physiquement les données, contrairement aux vues matérialisées.",
      "Elles ne peuvent concerner qu'une seule table"]),
    (31, False, "C", "Pourquoi la Vue_Medecins est-elle considérée comme une vue logique plutôt qu'une vue matérialisée ?",
     ["Elle est basée sur une seule table sans agrégation.",
      "Elle utilise une fonction dynamique (CURRENT_USER_ID()).",
      "Elle ne stocke pas physiquement les données.",
      "Elle permet des modifications sans restriction."]),
    (32, False, "D", "Que doit-on ajouter au moment de la création de la vue Vue_Medecins pour empêcher les requêtes de modification de ce type : UPDATE Vue_Medecins SET Diagnostic = 'Grippe' WHERE PatientID = 101; ?",
     ["La vue doit inclure toutes les colonnes de la table Patients.",
      "La vue doit contenir la clé primaire et ne pas inclure de jointures.",
      "Le médecin ne doit pas avoir le droit UPDATE sur la table Patients.",
      "La vue doit être définie avec l'option WITH CHECK OPTION."]),
    (33, False, "D", "Pourquoi les infirmiers n'ont-ils pas reçu le droit UPDATE sur Vue_Infirmiers ?",
     ["La vue inclut des colonnes sensibles comme le Diagnostic.",
      "Le droit UPDATE a été hérité de la table de base Patients.",
      "La vue est une vue matérialisée, donc non modifiable.",
      "Les infirmiers n'ont pas besoin de modifier les données pour leurs tâches."]),
    (34, False, "B", "Si un administrateur exécute SELECT * FROM Vue_Stats_Diagnostics à midi, que reflètent les données affichées ?",
     ["Les données des patients mises à jour en temps réel.",
      "Les données des patients telles qu'elles étaient lors du dernier rafraîchissement nocturne.",
      "Les données des patients agrégées uniquement pour la journée en cours.",
      "Les données des patients basées sur les transactions en cours."]),
    (35, False, "B", "Si vous souhaitez restreindre l'accès des médecins à Vue_Medecins pour qu'ils ne puissent voir que les patients de leur propre service (basé sur une table Services), comment modifieriez-vous la vue ?",
     ["Ajouter une clause GROUP BY pour regrouper par service.",
      "Inclure une jointure avec la table Services dans la définition de la vue.",
      "Supprimer la condition CURRENT_USER_ID() de la vue.",
      "Convertir la vue en une vue matérialisée."]),
    (36, False, "B", "Pourquoi la relation Livres n'est-elle pas en 2e forme normale (2FN) ?",
     ["Certaines dépendances sont erronées",
      "Certains attributs non-clés dépendent partiellement de la clé candidate.",
      "La clé primaire est composée de plusieurs attributs.",
      "Elle inclut des attributs qui ne sont pas fonctionnellement dépendants de la clé."]),
    (37, False, "B", "Quelle est la première étape pour décomposer la relation Livres en 2e forme normale (2FN) ?",
     ["Mettre la clef primaire de la relation à (ISBN, NomAuteur) au lieu de ISBN seulement",
      "Séparer les attributs qui dépendent partiellement de ISBN, comme EmailAuteur et AdresseEditeur.",
      "Regrouper tous les attributs non-clés dans une nouvelle relation.",
      "Supprimer les attributs NomAuteur et NomEditeur de la relation."]),
    (38, False, "C", "Après avoir décomposé Livres en 2FN, quelles relations pourraient être créées pour respecter cette forme ?",
     ["R1(ISBN, Titre, AnneePublication, Prix), R2(NomAuteur, EmailAuteur), R3(NomEditeur, AdresseEditeur)",
      "R1(ISBN, Titre, NomAuteur, EmailAuteur), R2(NomEditeur, AdresseEditeur, Prix)",
      "R1(ISBN, Titre, NomAuteur, NomEditeur, AnneePublication, Prix), R2(NomAuteur, EmailAuteur), R3(NomEditeur, AdresseEditeur)",
      "R1(ISBN, Titre, Prix), R2(NomAuteur, NomEditeur, EmailAuteur, AdresseEditeur)"]),
    (39, False, "D", "Considérons cette relation : R1(ISBN, Titre, NomAuteur, NomEditeur, AnneePublication, Prix). Pour atteindre la 3e forme normale (3FN) à partir de cette relation, quelle dépendance fonctionnelle doit être éliminée ?",
     ["ISBN -> Titre, AnneePublication, Prix", "NomAuteur -> EmailAuteur", "ISBN -> NomAuteur, NomEditeur", "Aucune, car R1 est déjà en 3NF"]),
    (40, False, "A", "Si vous utilisez l'algorithme de synthèse pour normaliser Livres directement en 3FN, quelle relation inclura la dépendance NomEditeur -> AdresseEditeur ?",
     ["Une relation contenant uniquement NomEditeur et AdresseEditeur.",
      "Une relation contenant ISBN, NomEditeur, et AdresseEditeur.",
      "Une relation contenant NomAuteur, NomEditeur, et AdresseEditeur.",
      "Une relation contenant tous les attributs de Livres."]),
]

questions = []
for num, multiple, letters, qtext, options in RAW:
    idx = {c: i for i, c in enumerate("ABCD")}
    correct = [options[idx[c]] for c in letters]
    item = {
        "id": f"bdd_de_{num:02d}",
        "question": qtext,
        "options": options,
        "sourceFile": SOURCE,
    }
    if multiple:
        item["multiple"] = True
        item["correctAnswers"] = correct
    else:
        item["correctAnswer"] = correct[0]
    questions.append(item)

out = Path(__file__).parent / "json" / "bdd.json"
out.write_text(json.dumps(questions, ensure_ascii=False, indent=2), encoding="utf-8")
print("OK:", len(questions), "questions")
